name: myASE_feats_env
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9.13
  - numpy=1.22.3
  - matplotlib=3.5.3
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - pip=22.1.2
  - spyder-kernels=2.1.0
  - scikit-learn=1.1.3
  - h5py=3.6.0
  - hdf5=1.10.6
  - pyyaml=6.0
  - tensorflow-gpu=2.6.0
  - pip:
    - pandas==2.0.2
    - cython==0.29.34
    - praat-parselmouth==0.4.3
