paths_config:
    data_file_path: 'data/train_data.mat' # The features files of the 136 recordings
    save_path: 'results/temp' # where to save the results
        
params_config:
    calculate: True
    n_out: 1
    act_out: "linear"
    loss_func: "mse" 
    metric: "mse"
    early_stopping: 
        eval: True
        patience: 20
    unite_test: True
    plot_TF: False # Do/dont create plots in the split function (target vs date, target hist)
    save_model: True # 08.03.22. If to save the model for each trial + the norm transformer
    model_name: "CNN_mdl" # The model'n name
    data_norm_by: "mat"
    score_name: "ADOS"
    norm_method: "standard" # features normalization method. z-norm.
    feats_take: 49 # number of first featuress to take
    num_mats_take: 5 # on how much matrices to run
    k_folds: 5
    i_mat: 0 # 0,1,2,...num_mats-1. from which feature matrix to start from
    valid_ratio: 0 # validation ratio from the training set. The validation data is selected from the last samples in the x and y data provided, before shuffling
    GPU_id: 0 #  0 or 1. on which GPU to run.
    gender: 'all' # 0 (=boys), 1 (=girls), 'all' in train set
    module: 'all' # [0,1,2,3]
    random_state: 1337
    
hyper_tune_config:
    calculate: 'tune' # tune, read (from the yaml file), or load (from the ready excel file)
    params_idx: 1 # 1,2,...,n_iters
    cv_k: 4 # number of folds to run the search tuning
    n_iters: 2 # number of combinations to check
    search_type: "rand"
    statistic: "CCC"
    batch_size:
        start: 3
        stop: 7
    n_epochs:
        start: 10
        stop: 2000
        step: 10
    learn_rate:
        start: -5
        stop: 0
    best_params: # in case where calculate="read"
        batch_size: 
        epochs:
        learn_rate: 